name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'bugfix'
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⚡ Performance'
    labels:
      - 'perf'
      - 'performance'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'refactor'
      - 'style'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'
  - title: '🔄 CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'workflow'
  - title: '↩️ Reverts'
    labels:
      - 'revert'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feat'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bug'
      - 'bugfix'
  default: patch
exclude-labels:
  - 'skip-changelog'
  - 'dependencies'
autolabeler:
  - label: 'feat'
    title:
      - '/^feat(\(.+\))?: .+/'
      - '/^feat(\(.+\))?!: .+/'
  - label: 'fix'
    title:
      - '/^fix(\(.+\))?: .+/'
      - '/^fix(\(.+\))?!: .+/'
  - label: 'docs'
    title:
      - '/^docs(\(.+\))?: .+/'
      - '/^docs(\(.+\))?!: .+/'
  - label: 'chore'
    title:
      - '/^chore(\(.+\))?: .+/'
      - '/^chore(\(.+\))?!: .+/'
  - label: 'test'
    title:
      - '/^test(\(.+\))?: .+/'
      - '/^test(\(.+\))?!: .+/'
  - label: 'ci'
    title:
      - '/^ci(\(.+\))?: .+/'
      - '/^ci(\(.+\))?!: .+/'
  - label: 'perf'
    title:
      - '/^perf(\(.+\))?: .+/'
      - '/^perf(\(.+\))?!: .+/'
  - label: 'refactor'
    title:
      - '/^refactor(\(.+\))?: .+/'
      - '/^refactor(\(.+\))?!: .+/'
  - label: 'style'
    title:
      - '/^style(\(.+\))?: .+/'
      - '/^style(\(.+\))?!: .+/'
  - label: 'revert'
    title:
      - '/^revert(\(.+\))?: .+/'
      - '/^revert(\(.+\))?!: .+/'
template: |
  $CHANGES

  ## Contributors

  $CONTRIBUTORS
